apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: api2-pod
spec: 
  replicas: 2 
  selector: 
    matchLabels:
      app: api2-pod
      version: v1 
  template: 
    metadata: 
      labels: 
        app: api2-pod
        version: v1
    spec: 
      containers: 
        - name: api
          image: vivekmore5292/vivek_cloudethix_nginx:v2
          ports:
            - containerPort: 80        