apiVersion: v1
kind: Service
metadata:
  name: haproxy-service
spec:
  selector:
    app: haproxy-pod
  ports:
    - name: port-80
      protocol: TCP
      port: 8080        
      targetPort: 8080
      nodePort: 30005
    - name: port-90
      protocol: TCP
      port: 8084        
      targetPort: 8404
      nodePort: 30004
  type: NodePort