apiVersion: apps/v1
kind: Deployment
metadata:
  name: submit-deploy
  labels:
    app: submit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: submit
  template:
    metadata:
      labels:
        app: submit
    spec:
      containers:
      - name: submit-pod
        image: vivekmore5292/submit:v1
        ports:
        - containerPort: 80
