apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
  Namespace: project-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: vivekmore5292/result
        name: result
        ports:
        - containerPort: 80
          name: result
